import type {
  PreCheckoutForm,
  PreCheckoutFormStep,
  PreCheckoutSystemMessages,
  PreCheckoutTemplateDefinition,
  PreCheckoutTemplateKey,
} from "@/types";

export const PRE_CHECKOUT_DEFAULT_THEME: PreCheckoutForm["theme"] = {
  style_key: "light",
  primary_color: "#111827",
  text_color: "#111827",
  panel_color: "#FFFFFF",
  background: {
    mode: "solid",
    color: "#F5F6FA",
    image_url: null,
    image_focus_x: 50,
    image_focus_y: 50,
  },
  typography: {
    heading_font: "Inter",
    body_font: "Inter",
    form_font: "Inter",
    button_radius: "md",
    input_radius: "md",
  },
  layout: {
    align: "center",
    spacing: "comfortable",
  },
  branding: {
    logo_url: null,
    logo_position: "center",
    logo_size: "md",
    background_image_url: null,
    background_image_focus_x: 50,
    background_image_focus_y: 50,
  },
};

export const PRE_CHECKOUT_SYSTEM_MESSAGE_DEFAULTS: PreCheckoutSystemMessages = {
  buttons: {
    confirm_answer: "OK",
    next_hint: "pressione Enter ↵",
    multiple_choice_hint: "Escolha quantas quiser",
    dropdown_hint: "Digite ou selecione uma opção",
    dropdown_touch_hint: "Selecione uma opção",
    other_label: "Outro",
    other_placeholder: "Digite sua resposta",
    exact_selection_step_1: "Escolha {min_selection}",
    exact_selection_step_2: "Escolha mais {additional_selections}",
    range_max_step_1: "Você pode escolher até {max_selection}",
    range_max_step_2: "Você pode escolher mais {additional_selections}",
    range_between: "Escolha entre {min_selection} e {max_selection} opções",
    range_min_step_1: "Escolha pelo menos {min_selection}",
    range_min_step_2: "Escolha pelo menos mais {additional_selections}",
    text_hint: "Digite sua resposta aqui...",
    option_key_hint: "Tecla",
    yes_label: "Sim",
    no_label: "Não",
    yes_shortcut: "Y",
    no_shortcut: "N",
    legal_accept_label: "Aceito",
    legal_reject_label: "Não aceito",
    review_label: "Revisar",
    submit_label: "Enviar",
    continue_label: "Continuar",
  },
  errors: {
    required: "Preencha este campo",
    selection_required: "Escolha uma opção para continuar",
    value_required: "Digite um valor para continuar",
    legal_rejected: "Você precisa aceitar para continuar",
    invalid_email: "Esse e-mail não parece válido",
    invalid_url: "Essa URL não parece válida",
    invalid_number_range: "Digite um número dentro do intervalo permitido",
    invalid_number_low: "Digite um número maior",
    invalid_number_high: "Digite um número menor",
    dropdown_not_found: "Nenhuma opção encontrada",
    invalid_phone: "Esse telefone não parece válido",
  },
  completion: {
    success: "Tudo certo. Obrigado pelo seu tempo.",
    no_connection: "Sem conexão com o servidor no momento",
    server_error: "O servidor não conseguiu concluir sua solicitação",
    unavailable: "Este form está indisponível no momento",
  },
  other: {
    unsupported_device: "Seu dispositivo abriu o form em modo simplificado.",
    line_break_hint: "Shift + Enter para quebrar a linha",
    file_required: "Envie um arquivo para continuar",
    file_button: "Escolher arquivo",
    file_drop_hint: "ou arraste aqui",
    file_too_big: "Esse arquivo é muito grande",
    file_uploading: "Seu arquivo ainda está sendo enviado, aguarde...",
  },
};

export const PRE_CHECKOUT_DEFAULT_SESSION_SETTINGS = {
  resume_window_minutes: 1440,
  abandonment_window_minutes: 60,
  system_messages: PRE_CHECKOUT_SYSTEM_MESSAGE_DEFAULTS,
} as PreCheckoutForm["session_settings"];

const baseSupports = {
  topImage: true,
  backgroundImage: true,
  redirect: true,
  pixel: true,
  workflow: true,
  ai: true,
};

export const PRE_CHECKOUT_TEMPLATES: Record<PreCheckoutTemplateKey, PreCheckoutTemplateDefinition> = {
  "lead-capture-classic": {
    key: "lead-capture-classic",
    version: 1,
    name: "Captação clássica",
    description: "Modelo direto para captar o lead com poucos passos.",
    category: "Captação",
    thumbnail: "gradient-lead-classic",
    supports: baseSupports,
    lockedFields: ["template_key", "template_version"],
    form: {
      name: "Form de captação",
      description: "Colete o essencial e leve o lead para a próxima ação.",
      theme: PRE_CHECKOUT_DEFAULT_THEME,
      final_config: {
        action: "thank_you",
        thank_you_title: "Tudo certo",
        thank_you_description: "Recebemos sua resposta.",
      },
      integrations: {
        tag_ids: [],
        pixel_enabled: true,
        workflows: [],
        connect: {
          meta_pixel_enabled: true,
          meta_pixel_id: "",
          ga4_enabled: false,
          ga4_measurement_id: "",
          gtm_enabled: false,
          gtm_container_id: "",
        },
      },
      session_settings: PRE_CHECKOUT_DEFAULT_SESSION_SETTINGS,
    },
    steps: [
      {
        step_key: "boas_vindas",
        position: 0,
        type: "welcome_screen",
        title: "Quase lá. Antes de continuar, responda rapidinho.",
        description: "Isso ajuda a personalizar a próxima etapa para você.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Começar" },
      },
      {
        step_key: "nome",
        position: 1,
        type: "short_text",
        title: "Qual é o seu nome?",
        description: "Quero te chamar do jeito certo na próxima etapa.",
        placeholder: "Digite seu nome",
        is_required: true,
        options: [],
        settings: { auto_focus: true, max_length: 120, map_to_contact_field: "name" },
      },
      {
        step_key: "telefone",
        position: 2,
        type: "phone",
        title: "Qual é o seu WhatsApp?",
        description: "É por onde vamos te avisar e acompanhar.",
        placeholder: "(11) 99999-9999",
        is_required: true,
        options: [],
        settings: { max_length: 24, map_to_contact_field: "phone" },
      },
      {
        step_key: "email",
        position: 3,
        type: "email",
        title: "Qual é o seu melhor e-mail?",
        description: "Vamos te enviar os próximos detalhes por aqui.",
        placeholder: "voce@exemplo.com",
        is_required: false,
        options: [],
        settings: { max_length: 160, map_to_contact_field: "email" },
      },
      {
        step_key: "final",
        position: 4,
        type: "end_screen",
        title: "Tudo certo. Agora vamos seguir.",
        description: "Clique abaixo para finalizar.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Finalizar" },
      },
    ],
  },
  "application-focus": {
    key: "application-focus",
    version: 1,
    name: "Aplicação e qualificação",
    description: "Modelo para filtrar melhor o lead antes do próximo passo.",
    category: "Qualificação",
    thumbnail: "gradient-application-focus",
    supports: baseSupports,
    lockedFields: ["template_key", "template_version"],
    form: {
      name: "Form de qualificação",
      description: "Descubra se o lead está no perfil certo antes de seguir.",
      theme: {
        ...PRE_CHECKOUT_DEFAULT_THEME,
        style_key: "light",
        text_color: "#12141A",
        panel_color: "#FFFFFF",
        background: {
          ...PRE_CHECKOUT_DEFAULT_THEME.background,
          color: "#F5F7FB",
        },
      },
      final_config: {
        action: "thank_you",
        thank_you_title: "Aplicação enviada",
        thank_you_description: "Agora vamos revisar seu perfil e te chamar no próximo passo.",
      },
      integrations: {
        tag_ids: [],
        pixel_enabled: true,
        workflows: [],
        connect: {
          meta_pixel_enabled: true,
          meta_pixel_id: "",
          ga4_enabled: false,
          ga4_measurement_id: "",
          gtm_enabled: false,
          gtm_container_id: "",
        },
      },
      session_settings: PRE_CHECKOUT_DEFAULT_SESSION_SETTINGS,
    },
    steps: [
      {
        step_key: "boas_vindas",
        position: 0,
        type: "welcome_screen",
        title: "Vamos entender seu cenário antes de seguir.",
        description: "É rápido e ajuda a personalizar a próxima etapa.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Começar" },
      },
      {
        step_key: "nome",
        position: 1,
        type: "short_text",
        title: "Como você quer ser chamado?",
        description: "",
        placeholder: "Seu nome",
        is_required: true,
        options: [],
        settings: { auto_focus: true, max_length: 120, map_to_contact_field: "name" },
      },
      {
        step_key: "faturamento",
        position: 2,
        type: "single_choice",
        title: "Qual faixa de faturamento atual do seu negócio?",
        description: "Isso nos ajuda a personalizar a próxima etapa.",
        placeholder: "",
        is_required: true,
        options: [
          { id: "ate-10k", label: "Até R$ 10 mil", value: "ate-10k" },
          { id: "10k-30k", label: "De R$ 10 mil a R$ 30 mil", value: "10k-30k" },
          { id: "30k-100k", label: "De R$ 30 mil a R$ 100 mil", value: "30k-100k" },
          { id: "100k-plus", label: "Acima de R$ 100 mil", value: "100k-plus" },
        ],
        settings: {},
      },
      {
        step_key: "telefone",
        position: 3,
        type: "phone",
        title: "Qual é o seu WhatsApp principal?",
        description: "Se fizer sentido, seguimos por aqui.",
        placeholder: "(11) 99999-9999",
        is_required: true,
        options: [],
        settings: { max_length: 24, map_to_contact_field: "phone" },
      },
      {
        step_key: "final",
        position: 4,
        type: "end_screen",
        title: "Aplicação enviada com sucesso.",
        description: "Agora vamos analisar seu perfil e te chamar no próximo passo.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Finalizar" },
      },
    ],
  },
  "warmup-whatsapp": {
    key: "warmup-whatsapp",
    version: 1,
    name: "Aquecimento para WhatsApp",
    description: "Modelo rápido para levar o lead para a conversa certa.",
    category: "WhatsApp",
    thumbnail: "gradient-whatsapp-warmup",
    supports: baseSupports,
    lockedFields: ["template_key", "template_version"],
    form: {
      name: "Form com saída para WhatsApp",
      description: "Capture intenção e continue o atendimento com contexto.",
      theme: {
        ...PRE_CHECKOUT_DEFAULT_THEME,
        primary_color: "#22C55E",
      },
      final_config: {
        action: "whatsapp_redirect",
        whatsapp_phone: "",
        whatsapp_message: "Olá! Acabei de preencher o formulário e quero continuar.",
      },
      integrations: {
        tag_ids: [],
        pixel_enabled: true,
        workflows: [],
        connect: {
          meta_pixel_enabled: true,
          meta_pixel_id: "",
          ga4_enabled: false,
          ga4_measurement_id: "",
          gtm_enabled: false,
          gtm_container_id: "",
        },
      },
      session_settings: PRE_CHECKOUT_DEFAULT_SESSION_SETTINGS,
    },
    steps: [
      {
        step_key: "boas_vindas",
        position: 0,
        type: "welcome_screen",
        title: "Vamos te levar para o WhatsApp certo.",
        description: "Antes disso, precisamos de duas respostas rápidas.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Começar" },
      },
      {
        step_key: "nome",
        position: 1,
        type: "short_text",
        title: "Qual é o seu nome?",
        description: "",
        placeholder: "Digite seu nome",
        is_required: true,
        options: [],
        settings: { auto_focus: true, max_length: 120, map_to_contact_field: "name" },
      },
      {
        step_key: "objetivo",
        position: 2,
        type: "long_text",
        title: "O que você quer resolver agora?",
        description: "Quanto melhor você responder, melhor será o atendimento no WhatsApp.",
        placeholder: "Conte brevemente o seu cenário",
        is_required: true,
        options: [],
        settings: { max_length: 500 },
      },
      {
        step_key: "telefone",
        position: 3,
        type: "phone",
        title: "Qual é o seu melhor número de contato?",
        description: "",
        placeholder: "(11) 99999-9999",
        is_required: true,
        options: [],
        settings: { max_length: 24, map_to_contact_field: "phone" },
      },
      {
        step_key: "final",
        position: 4,
        type: "end_screen",
        title: "Perfeito. Vamos abrir o WhatsApp com contexto.",
        description: "Clique abaixo para continuar a conversa.",
        placeholder: "",
        is_required: false,
        options: [],
        settings: { button_label: "Abrir WhatsApp" },
      },
    ],
  },
};

export const PRE_CHECKOUT_TEMPLATE_LIST = Object.values(PRE_CHECKOUT_TEMPLATES);

function deepClone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function getPreCheckoutTemplate(templateKey: string): PreCheckoutTemplateDefinition | null {
  return PRE_CHECKOUT_TEMPLATES[templateKey as PreCheckoutTemplateKey] || null;
}

export function buildFormFromTemplate(templateKey: string): {
  form: Omit<PreCheckoutForm, "id" | "user_id" | "slug" | "status" | "published_at" | "archived_at" | "created_at" | "updated_at"> & { name: string };
  steps: Array<Omit<PreCheckoutFormStep, "id" | "form_id" | "created_at" | "updated_at">>;
} | null {
  const template = getPreCheckoutTemplate(templateKey);
  if (!template) return null;

  return {
    form: {
      name: template.form.name,
      description: template.form.description,
      template_key: template.key,
      template_version: template.version,
      theme: deepClone(template.form.theme),
      final_config: deepClone(template.form.final_config),
      integrations: deepClone(template.form.integrations),
      session_settings: deepClone(template.form.session_settings),
    },
    steps: template.steps.map((step) => ({
      step_key: step.step_key,
      position: step.position,
      type: step.type,
      title: step.title,
      description: step.description,
      placeholder: step.placeholder,
      is_required: step.is_required,
      options: deepClone(step.options),
      settings: deepClone(step.settings),
    })),
  };
}
